FROM node:20.3.1-alpine

RUN apk -U upgrade && apk add --no-cache curl git

WORKDIR /opt/app

COPY package.json package-lock.json ./

RUN rm -rf node_modules && \
    rm -rf .next && \
    npm i

CMD ["npm", "run", "dev"]
