FROM node:20.3.1-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl git && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY package.json package-lock.json ./

RUN rm -rf node_modules && \
    rm -rf .next && \
    npm i

CMD ["npm", "run", "dev"]
