version: '3.7'
services:
  web:
    stdin_open: true
    tty: true
    container_name: portfolio_frontend
    build:
      context: .
      dockerfile: ./Dockerfile.web
    volumes:
      - ./:/opt/app
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
    healthcheck:
      test: curl --fail portfolio_frontend:3000/api/health || exit 1
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 10s
    networks:
      - backend-network

networks:
  backend-network:
    external: true
