# Dockerfile production version
FROM node:20.3.1-alpine

RUN apk -U upgrade && apk add --no-cache curl git bash

WORKDIR /opt/app

COPY package.json package-lock.json ./

RUN rm -rf node_modules && \
    rm -rf .next && \
    npm ci

COPY src ./src
COPY public ./public
COPY postcss.config.mjs tailwind.config.ts \
     next.config.ts tsconfig.json ./

RUN npm run build

CMD ["npm", "run", "start"]
