name: portfolio-ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Check version npm and install the dependencies
        run: |
          npm -v
          npm i
      - name: Lint and build application
        run: |
          npm run lint
          npm run build